### PR TITLE
Implemented hierarchy cache

### PR DESCRIPTION
**Pull request by tobyryuk**
Not sure if this was what you were looking for, reviewed the predis version and it looked like all it needed was some copy and paste?

### CODE REVIEW

**Comment by tobyryuk** [comment]
Didn't add tests since I'm not 100% sure about how to use Redis properly.

**Comment by Nyholm** [comment]
Thank you. It looks really good. 

Can you also add the integration tests? You don't need to write the test yourself, you just have to extend HierarchicalCachePoolTest like this: https://github.com/php-cache/predis-adapter/blob/master/tests/IntegrationHierarchyTest.php

Aslo, there are some style fixes you need to `git apply patch.txt`

**Comment by tobyryuk** [comment]
Not sure how to apply style fixes. Never used StyleCI before.

**Comment by tobyryuk** [comment]
Seems like I figured it out.

**Comment by Nyholm** [comment]
Awesome! Thank you for this PR!

If you like to you can do the same with the [Memcached](https://github.com/php-cache/memcached-adapter) adapter.

**Pull request merged**
